wallpaper {
    monitor = eDP-1
    path = /home/tieppo/.local/share/wallpapers/alone.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/tieppo/.local/share/wallpapers/alone.png
    fit_mode = cover
}
