[general]
; temperatura de dia (padrão) e de noite
temp-day=6500
temp-night=2000

; modo por horário (NÃO usa geoclue2 nem localização)
; dusk = entra na noite | dawn = sai da noite
dusk-time=21:30
dawn-time=8:30

; fade suave ao iniciar/parar
fade=1

; descomente conforme seu servidor gráfico:
;adjustment-method=wayland
;adjustment-method=randr
