#!/usr/bin/env bash

case $1 in
    input)
        TARGET="@DEFAULT_SOURCE@"
        STATE_CMD="source-mute"
        VOL_CMD="source-volume"
        ICON="mic-volume"
        NAME="Microphone"
        ;;
    output)
        TARGET="@DEFAULT_SINK@"
        STATE_CMD="sink-mute"
        VOL_CMD="sink-volume"
        ICON="audio-volume"
        NAME="Volume"
        ;;
    *) 
        echo "Uso: $0 [input|output] [mute|raise|lower] [passo]"
        exit 1 
        ;;
esac

get_vol() { 
    pactl "get-$VOL_CMD" "$TARGET" | grep -Po '[0-9]{1,3}(?=%)' | head -n 1
}

get_mute() { 
    pactl "get-$STATE_CMD" "$TARGET" | grep -iq "yes" && echo "Muted" || echo "Unmuted"
}

case $2 in
    mute)
        pactl "set-$STATE_CMD" "$TARGET" toggle
        STATE=$(get_mute)

        if [ "$STATE" == "Muted" ]; then
            I="$ICON-muted"
        else
            I="$ICON-high"
        fi

        notify-send "$NAME" "$STATE" -i "$I" \
            -h string:x-canonical-private-synchronous:volume
        ;;
 
    raise|lower)
        STEP=${3:-1}
        [[ "$2" == "raise" ]] && OP="+" || OP="-"

        CURRENT_VOL=$(get_vol)
        NEW_VOL=$((CURRENT_VOL $OP STEP))

        (( NEW_VOL > 100 )) && NEW_VOL=100
        (( NEW_VOL < 0 )) && NEW_VOL=0

        pactl "set-$VOL_CMD" "$TARGET" "$NEW_VOL%"

        if [ "$(get_mute)" == "Muted" ]; then
            I="$ICON-muted"
        elif (( NEW_VOL < 33 )); then 
            I="$ICON-low"
        elif (( NEW_VOL < 66 )); then 
            I="$ICON-medium"
        else 
            I="$ICON-high"
        fi

        hyprctl notify -1 5000 "$NAME" "$NEW_VOL%" -i "$I" \
            -h int:value:"$NEW_VOL" \
            -h string:x-canonical-private-synchronous:volume
        ;;
esac
